# SmartInternz Externship Program - Applied Data Science - Assignment 1

### Name: Sanskriti Sanjay Kumar Singh <br> Reg No: 20BCE1415 <br> Email: sanskriti.sanjaykumar2020@&#65279;vitstudent.ac.in <br> Campus: VIT Chennai

## Question 1: Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.

In [1]:
# Assigning value to variables
name = 'Sanskriti Sanjay Kumar Singh'
age = 20

In [2]:
# Printing name and age
print('Name: ',name,'\nAge: ',age)

Name:  Sanskriti Sanjay Kumar Singh 
Age:  20


## Question 2: X="Datascience is used to extract meaningful insights." Split the string.

In [3]:
X = "Datascience is used to extract meaningful insights."

In [4]:
# Splitting the string by assuming delimiter as space(' ') i.e. the default delimiter for the split() function
lst = X.split()
print(lst)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


## Question 3: Make a function that gives multiplication of two numbers.

In [5]:
# Defining the function that gives multiplication of two numbers
def mult(num1,num2):
    return num1*num2

In [6]:
# Taking the two numbers as input and printing the product of the two numbers
a = int(input('Enter first number: '))
b = int(input('Enter second number: '))
print(mult(a,b))

Enter first number: 23
Enter second number: 54
1242


## Question 4: Create a Dictionary of 5 States with their capitals. Also print the keys and values.

In [7]:
# Creating the dictionary of 5 states as keys and their capitals as values
d = {'Assam':'Dispur',
     'Bihar':'Patna',
     'Gujarat':'Gandhinagar',
     'Kerala':'Thiruvananthapuram',
     'Tamil Nadu':'Chennai'}

In [8]:
# Printing the Keys
print('Keys:',end=' ')
for k in d.keys():
    print(k,end=' ')

Keys: Assam Bihar Gujarat Kerala Tamil Nadu 

In [9]:
# Printing the Values
print('Values:',end=' ')
for v in  d.values():
    print(v,end=' ')

Values: Dispur Patna Gandhinagar Thiruvananthapuram Chennai 

## Question 5: Create a list of 1000 numbers using range function.

In [10]:
# Creating a list of 1000 numbers using range() function (Assuming numbers are to be created sequentially)
lst = [num for num in range(1,1001)]

In [11]:
# Printing the length of the list
len(lst)

1000

In [12]:
# Printing the list
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

## Question 6: Create an identity matrix of dimension 4 by 4

In [13]:
# Importing the required NumPy library
import numpy as np

In [14]:
# Creating the 4x4 identity matrix
I = np.eye(4)

In [15]:
# Printing the identity matrix
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Question 7: Create a 3x3 matrix with values ranging from 1 to 9

In [16]:
# Note: NumPy library already imported in Question 6

In [17]:
# Case 1: Creating the 3x3 matrix, assuming sequential values ranging from 1 to 9
mat1 = np.arange(1,10).reshape(3,3)

In [18]:
# Printing the matrix
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# Case 2: Creating the 3x3 matrix, assuming random values ranging from 1 to 9
mat2 = np.random.randint(1,10,9).reshape(3,3)

In [20]:
# Printing the matrix
print(mat2)

[[1 5 3]
 [2 5 6]
 [3 7 4]]


## Question 8: Create 2 similar dimensional array and perform sum on them.

In [21]:
# Note: NumPy library already imported in Question 6

In [22]:
# Creating two 2-dimensional 3x4 arrays (i.e. arrays having 3 rows and 4 columns) having numbers ranging from 1 to 100
a1 = np.random.randint(1,101,12).reshape(3,4)
a2 = np.random.randint(1,101,12).reshape(3,4)

In [23]:
# Printing the two arrays
print('Array 1:\n',a1)
print('---------------')
print('Array 2:\n',a2)

Array 1:
 [[71 41 68  7]
 [21 61 70  4]
 [63 94  6 81]]
---------------
Array 2:
 [[47  8 78 69]
 [88  9 94 21]
 [88 94 29 56]]


In [24]:
# Summing up the two arrays
s = np.add(a1,a2)

In [25]:
# Printing the resultant array
print(s)

[[118  49 146  76]
 [109  70 164  25]
 [151 188  35 137]]


## Question 9: Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

In [26]:
# Importing the required Pandas library
import pandas as pd

In [27]:
# Generating the series of dates from 1st february 2023 to 1st march 2023 (both inclusive)
s = pd.Series(pd.date_range(start = '2023-02-01', end = '2023-03-01', inclusive = 'both'))

In [28]:
# Printing the series
print(s)

0    2023-02-01
1    2023-02-02
2    2023-02-03
3    2023-02-04
4    2023-02-05
5    2023-02-06
6    2023-02-07
7    2023-02-08
8    2023-02-09
9    2023-02-10
10   2023-02-11
11   2023-02-12
12   2023-02-13
13   2023-02-14
14   2023-02-15
15   2023-02-16
16   2023-02-17
17   2023-02-18
18   2023-02-19
19   2023-02-20
20   2023-02-21
21   2023-02-22
22   2023-02-23
23   2023-02-24
24   2023-02-25
25   2023-02-26
26   2023-02-27
27   2023-02-28
28   2023-03-01
dtype: datetime64[ns]


## Question 10: Given a dictionary, convert it into corresponding dataframe and display it dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [29]:
# Note: Pandas library already imported in Question 9

In [30]:
# Creating the given dictionary
dictionary = {'Brand':['Maruti','Renault','Hyundai'],'Sales':[250,200,240]}

In [31]:
# Converting the dictionary into dataframe
df = pd.DataFrame(dictionary)

In [32]:
# Displaying/Printing the dataframe
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
